[workspace]
members = ["safe-cli", "safe-api", "safe-ffi", "safe-authd", "jsonrpc-quic"]


[patch.crates-io]
self_update = { git = "https://github.com/joshuef/self_update.git", rev = "9a15014c31096b8f35da2e439aaf1b560deb0a16" }
